In [2]:
import numpy as np

## Задание 1

In [18]:
N = 10
n = np.arange(N)[::-1]
print(n)

[9 8 7 6 5 4 3 2 1 0]


## Задание 2

In [26]:
d = np.diag(n)
print(d)
print(f'\nСумма по диагонали: {n.sum()}')

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]

Сумма по диагонали: 45


## Задание 3

In [48]:
coef = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
res = np.array([4, 12, -3])
xyz = np.linalg.solve(coef, res)
print(f'x = {xyz[0]:.2f}, y = {xyz[1]:.2f}, z = {xyz[2]:.2f}')

x = 0.47, y = 3.84, z = -5.56


## Задание 4

In [55]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])


In [125]:
def cos_lngth(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

In [133]:
min_cos_lngth = 0
for i, row in enumerate(users_stats):
    curr_cos_lngth = cos_lngth(row, next_user_stats)
    if curr_cos_lngth > min_cos_lngth:
        min_cos_lngth = curr_cos_lngth
        user_id = i + 1

print(f'Самый похожий пользователь с ИД = {user_id}')

Самый похожий пользователь с ИД = 8
